#include <gtest/gtest.h>
#include <chrono>
#include <iostream>
#include <sstream>
#include <thread>

#include "Timer.hpp"

// These tests were partially generated by Claude

using namespace RTB;

class TimerTest : public ::testing::Test {
   protected:
    void SetUp() override {
        // Redirect cout to capture output
        original_cout = std::cout.rdbuf();
        std::cout.rdbuf(buffer.rdbuf());
    }

    void TearDown() override {
        // Restore cout
        std::cout.rdbuf(original_cout);
    }

    std::string GetOutput() {
        return buffer.str();
    }

    void ClearOutput() {
        buffer.str("");
        buffer.clear();
    }

   private:
    std::stringstream buffer;
    std::streambuf* original_cout;
};

// Test Timer basic functionality
TEST_F(TimerTest, TimerStartsAutomatically) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(10));

    float elapsed_ms = timer.Elapsed<std::chrono::milliseconds>();
    EXPECT_GT(elapsed_ms, 5.0f);  // Should be at least 5ms
    EXPECT_LT(elapsed_ms,
              50.0f);  // Should be less than 50ms (generous upper bound)
}

TEST_F(TimerTest, ManualStartWorks) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(5));

    timer.Start();  // Reset the timer
    std::this_thread::sleep_for(std::chrono::milliseconds(10));

    float elapsed_ms = timer.Elapsed<std::chrono::milliseconds>();
    EXPECT_GT(elapsed_ms, 5.0f);
    EXPECT_LT(elapsed_ms, 30.0f);
}

TEST_F(TimerTest, SecondsResolution) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(100));

    float elapsed_s = timer.Elapsed<std::chrono::seconds>();;
    EXPECT_GT(elapsed_s, 0.05f);  // Should be at least 0.05 seconds
    EXPECT_LT(elapsed_s, 0.5f);   // Should be less than 0.5 seconds
}

TEST_F(TimerTest, MillisecondsResolution) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(50));

    float elapsed_ms = timer.Elapsed<std::chrono::milliseconds>();
    EXPECT_GT(elapsed_ms, 25.0f);
    EXPECT_LT(elapsed_ms, 200.0f);
}

TEST_F(TimerTest, MicrosecondsResolution) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(10));

    float elapsed_us = timer.Elapsed<std::chrono::microseconds>();
    EXPECT_GT(elapsed_us, 5000.0f);   // Should be at least 5000 microseconds
    EXPECT_LT(elapsed_us, 50000.0f);  // Should be less than 50000 microseconds
}

TEST_F(TimerTest, NanosecondsResolution) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(5));

    float elapsed_ns = timer.Elapsed<std::chrono::nanoseconds>();
    EXPECT_GT(elapsed_ns,
              1000000.0f);  // Should be at least 1,000,000 nanoseconds
}

TEST_F(TimerTest, InvalidResolutionReturnsNanoseconds) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(5));

    float elapsed_invalid = timer.Elapsed();
    float elapsed_ns = timer.Elapsed<std::chrono::nanoseconds>();

    // Both should return nanoseconds when invalid resolution is used
    EXPECT_GT(elapsed_invalid, 1000000.0f);
    // Note: We can't directly compare them since time has passed between calls
}

TEST_F(TimerTest, StopAndPrintOutputsCorrectFormat) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(10));

    timer.Print<std::chrono::milliseconds>();
    std::string output = GetOutput();

    EXPECT_TRUE(output.find("[TIMER]") != std::string::npos);
    EXPECT_TRUE(output.find("ms") != std::string::npos);
    EXPECT_TRUE(output.find(" - ") != std::string::npos);
}

TEST_F(TimerTest, MultipleStopAndCountCalls) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(10));

    float first_call = timer.Elapsed<std::chrono::milliseconds>();
    std::this_thread::sleep_for(std::chrono::milliseconds(5));
    float second_call = timer.Elapsed<std::chrono::milliseconds>();

    // Second call should be larger since more time has passed
    EXPECT_GT(second_call, first_call);
}

// Test ScopedTimer functionality
TEST_F(TimerTest, ScopedTimerPrintsOnDestruction) {
    {
        ScopedTimer<std::chrono::milliseconds> scoped_timer("TestOperation");
        std::this_thread::sleep_for(std::chrono::milliseconds(10));
    }  // Destructor should be called here

    std::string output = GetOutput();
    EXPECT_TRUE(output.find("[TIMER]") != std::string::npos);
    EXPECT_TRUE(output.find("TestOperation") != std::string::npos);
    EXPECT_TRUE(output.find("ms") != std::string::npos);
}

TEST_F(TimerTest, ScopedTimerWithDifferentResolutions) {
    ClearOutput();
    {
        ScopedTimer<std::chrono::seconds> scoped_timer("SecondsTest");
        std::this_thread::sleep_for(std::chrono::milliseconds(50));
    }

    std::string output = GetOutput();
    EXPECT_TRUE(output.find("SecondsTest") != std::string::npos);
    EXPECT_TRUE(output.find(" s") != std::string::npos);
}

TEST_F(TimerTest, ScopedTimerMeasuresCorrectTime) {
    std::chrono::milliseconds sleep_duration(20);

    {
        ScopedTimer<std::chrono::milliseconds> scoped_timer("TimingTest");
        std::this_thread::sleep_for(sleep_duration);
    }

    std::string output = GetOutput();

    // Extract the time value from output (this is a bit hacky but works for
    // testing)
    size_t dash_pos = output.find(" - ");
    size_t ms_pos = output.find(" ms");
    if (dash_pos != std::string::npos && ms_pos != std::string::npos) {
        std::string time_str =
            output.substr(dash_pos + 3, ms_pos - dash_pos - 3);
        float measured_time = std::stof(time_str);

        // Should be at least 10ms and less than 100ms
        EXPECT_GT(measured_time, 10.0f);
        EXPECT_LT(measured_time, 100.0f);
    }
}

TEST_F(TimerTest, MultipleScopedTimers) {
    ClearOutput();

    {
        ScopedTimer<std::chrono::milliseconds> timer1("First");
        std::this_thread::sleep_for(std::chrono::milliseconds(5));

        {
            ScopedTimer<std::chrono::microseconds> timer2("Second");
            std::this_thread::sleep_for(std::chrono::milliseconds(5));
        }  // timer2 destructs first

        std::this_thread::sleep_for(std::chrono::milliseconds(5));
    }  // timer1 destructs second

    std::string output = GetOutput();

    // Should contain both timer outputs
    EXPECT_TRUE(output.find("First") != std::string::npos);
    EXPECT_TRUE(output.find("Second") != std::string::npos);
    EXPECT_TRUE(output.find(" ms") != std::string::npos);
    EXPECT_TRUE(output.find(" us") != std::string::npos);
}

// Test edge cases
TEST_F(TimerTest, VeryShortDuration) {
    Timer timer;
    // Don't sleep, just measure immediately

    float elapsed_ns = timer.Elapsed<std::chrono::nanoseconds>();
    EXPECT_GE(elapsed_ns, 0.0f);  // Should be non-negative
}

TEST_F(TimerTest, ConversionAccuracy) {
    Timer timer;
    std::this_thread::sleep_for(std::chrono::milliseconds(100));

    float elapsed_s = timer.Elapsed<std::chrono::seconds>();
    timer.Start();  // Reset
    std::this_thread::sleep_for(std::chrono::milliseconds(100));
    float elapsed_ms = timer.Elapsed<std::chrono::milliseconds>();

    // 100ms should be approximately 0.1s
    // Allow for some timing variance
    EXPECT_NEAR(elapsed_s, elapsed_ms / 1000.0f, 0.05f);
}