#include <gtest/gtest.h>

#include <RTB/Vector.hpp>

using namespace RTB;

// These tests were partially generated by Claude

using Vec3 = Vector<double, 3>;
using Point3 = Point<double, 3>;

TEST(VectorTest, DefaultConstructor) {
    Vec3 v;
    for (size_t i = 0; i < 3; ++i)
        EXPECT_EQ(v[i], 0.0);
}

TEST(VectorTest, InitializerListConstructor) {
    Vec3 v{1.0, 2.0, 3.0};
    EXPECT_EQ(v[0], 1.0);
    EXPECT_EQ(v[1], 2.0);
    EXPECT_EQ(v[2], 3.0);
}

TEST(VectorTest, ArrayConstructor) {
    std::array<double, 3> arr = {4.0, 5.0, 6.0};
    Vec3 v(arr);
    EXPECT_EQ(v.GetComponents(), arr);
}

TEST(VectorTest, PointConstructor) {
    Point3 p1{1.0, 2.0, 3.0};
    Vec3 v(p1);
    EXPECT_EQ(v[0], 1.0);
    EXPECT_EQ(v[1], 2.0);
    EXPECT_EQ(v[2], 3.0);
}

TEST(VectorTest, TwoPointConstructor) {
    Point3 p1{1.0, 1.0, 1.0};
    Point3 p2{4.0, 5.0, 6.0};
    Vec3 v(p1, p2);
    EXPECT_EQ(v[0], 3.0);
    EXPECT_EQ(v[1], 4.0);
    EXPECT_EQ(v[2], 5.0);
}

TEST(VectorTest, SetAndGetComponents) {
    Vec3 v;
    std::array<double, 3> components = {7.0, 8.0, 9.0};
    v.SetComponents(components);
    EXPECT_EQ(v.GetComponents(), components);
}

TEST(VectorTest, IndexOperator) {
    Vec3 v{1.0, 2.0, 3.0};
    EXPECT_EQ(v[0], 1.0);
    EXPECT_EQ(v[1], 2.0);
    EXPECT_EQ(v[2], 3.0);

    // Test modification through index
    v[1] = 10.0;
    EXPECT_EQ(v[1], 10.0);
}

TEST(VectorTest, ArithmeticOperatorsScalar) {
    Vec3 v{1.0, 2.0, 3.0};
    auto v2 = v + 2.0;
    EXPECT_EQ(v2, Vec3({3.0, 4.0, 5.0}));

    v2 = v - 1.0;
    EXPECT_EQ(v2, Vec3({0.0, 1.0, 2.0}));

    v2 = v * 2.0;
    EXPECT_EQ(v2, Vec3({2.0, 4.0, 6.0}));

    v2 = v / 2.0;
    EXPECT_EQ(v2, Vec3({0.5, 1.0, 1.5}));
}

TEST(VectorTest, ArithmeticOperatorsVector) {
    Vec3 v1{1.0, 2.0, 3.0};
    Vec3 v2{4.0, 5.0, 6.0};

    EXPECT_EQ(v1 + v2, Vec3({5.0, 7.0, 9.0}));
    EXPECT_EQ(v2 - v1, Vec3({3.0, 3.0, 3.0}));
    EXPECT_EQ(v1 * v2, Vec3({4.0, 10.0, 18.0}));
}

TEST(VectorTest, CompoundAssignmentOperators) {
    Vec3 v{1.0, 2.0, 3.0};
    v += 1.0;
    EXPECT_EQ(v, Vec3({2.0, 3.0, 4.0}));

    v -= 1.0;
    EXPECT_EQ(v, Vec3({1.0, 2.0, 3.0}));

    v *= 2.0;
    EXPECT_EQ(v, Vec3({2.0, 4.0, 6.0}));

    v /= 2.0;
    EXPECT_EQ(v, Vec3({1.0, 2.0, 3.0}));

    Vec3 other{1.0, 1.0, 1.0};
    v += other;
    EXPECT_EQ(v, Vec3({2.0, 3.0, 4.0}));

    v -= other;
    EXPECT_EQ(v, Vec3({1.0, 2.0, 3.0}));

    v *= other;
    EXPECT_EQ(v, Vec3({1.0, 2.0, 3.0}));
}

TEST(VectorTest, ScalarOperatorsCommutative) {
    Vec3 v{1.0, 2.0, 3.0};

    // Test scalar + vector
    EXPECT_EQ(2.0 + v, Vec3({3.0, 4.0, 5.0}));
    EXPECT_EQ(v + 2.0, 2.0 + v);

    // Test scalar * vector
    EXPECT_EQ(3.0 * v, Vec3({3.0, 6.0, 9.0}));
    EXPECT_EQ(v * 3.0, 3.0 * v);

    // Test scalar - vector (not commutative)
    EXPECT_EQ(5.0 - v, Vec3({4.0, 3.0, 2.0}));
}

TEST(VectorTest, UnaryMinus) {
    Vec3 v{1.0, -2.0, 3.0};
    Vec3 negated = -v;
    EXPECT_EQ(negated, Vec3({-1.0, 2.0, -3.0}));

    // Original should be unchanged
    EXPECT_EQ(v, Vec3({1.0, -2.0, 3.0}));
}

TEST(VectorTest, LengthCalculations) {
    Vec3 v{3.0, 4.0, 0.0};
    EXPECT_DOUBLE_EQ(v.MagnitudeSquared(), 25.0);
    EXPECT_DOUBLE_EQ(v.Magnitude(), 5.0);
}

TEST(VectorTest, Normalize) {
    Vec3 v{0.0, 3.0, 4.0};
    Vec3 original = v;  // Keep copy of original

    // Test Normalize() - returns new normalized vector, original unchanged
    Vec3 normalized = v.Normalize();
    EXPECT_NEAR(normalized[0], 0.0, 1e-9);
    EXPECT_NEAR(normalized[1], 0.6, 1e-9);
    EXPECT_NEAR(normalized[2], 0.8, 1e-9);
    EXPECT_NEAR(normalized.Magnitude(), 1.0, 1e-9);

    // Original should be unchanged
    EXPECT_EQ(v, original);
}

TEST(VectorTest, NormalizeInPlace) {
    Vec3 v{0.0, 3.0, 4.0};

    // Test NormalizeInPlace() - modifies original vector
    Vec3& result = v.NormalizeInPlace();
    EXPECT_NEAR(v[0], 0.0, 1e-9);
    EXPECT_NEAR(v[1], 0.6, 1e-9);
    EXPECT_NEAR(v[2], 0.8, 1e-9);
    EXPECT_NEAR(v.Magnitude(), 1.0, 1e-9);

    // Should return reference to self for chaining
    EXPECT_EQ(&result, &v);
}

TEST(VectorTest, NormalizeZeroVector) {
    Vec3 zero{0.0, 0.0, 0.0};

    // Normalize of zero vector should return zero vector
    Vec3 normalized = zero.Normalize();
    EXPECT_EQ(normalized, zero);

    // NormalizeInPlace of zero vector should leave it unchanged
    Vec3 zero2{0.0, 0.0, 0.0};
    zero2.NormalizeInPlace();
    EXPECT_EQ(zero2, Vec3({0.0, 0.0, 0.0}));
}

TEST(VectorTest, Invert) {
    Vec3 v{1.0, -2.0, 3.0};
    Vec3& result = v.Invert();
    EXPECT_EQ(v, Vec3({-1.0, 2.0, -3.0}));

    // Should return reference to self for chaining
    EXPECT_EQ(&result, &v);
}

TEST(VectorTest, ChainOperations) {
    Vec3 v{0.0, 6.0, 8.0};

    // Test method chaining
    v.NormalizeInPlace().Invert();
    EXPECT_NEAR(v[0], 0.0, 1e-9);
    EXPECT_NEAR(v[1], -0.6, 1e-9);
    EXPECT_NEAR(v[2], -0.8, 1e-9);
}

TEST(VectorTest, DotProduct) {
    Vec3 v1{1.0, 2.0, 3.0};
    Vec3 v2{4.0, -5.0, 6.0};
    EXPECT_DOUBLE_EQ(DotProduct(v1, v2), 12.0);

    // Test with different types
    Vector<float, 3> vf{1.0f, 2.0f, 3.0f};
    Vector<double, 3> vd{4.0, -5.0, 6.0};
    auto result = DotProduct(vf, vd);
    EXPECT_DOUBLE_EQ(result, 12.0);
}

TEST(VectorTest, CrossProduct) {
    Vec3 v1{1.0, 0.0, 0.0};
    Vec3 v2{0.0, 1.0, 0.0};
    auto cross = CrossProduct(v1, v2);
    EXPECT_EQ(cross, Vec3({0.0, 0.0, 1.0}));

    // Test anti-commutativity: v1 × v2 = -(v2 × v1)
    auto cross_reverse = CrossProduct(v2, v1);
    EXPECT_EQ(cross_reverse, Vec3({0.0, 0.0, -1.0}));

    // Test with different types
    Vector<float, 3> vf{1.0f, 0.0f, 0.0f};
    Vector<double, 3> vd{0.0, 1.0, 0.0};
    auto mixed_cross = CrossProduct(vf, vd);
    EXPECT_EQ(mixed_cross, Vec3({0.0, 0.0, 1.0}));
}

TEST(VectorTest, EqualityOperators) {
    Vec3 v1{1.0, 2.0, 3.0};
    Vec3 v2{1.0, 2.0, 3.0};
    Vec3 v3{3.0, 2.0, 1.0};

    EXPECT_TRUE(v1 == v2);
    EXPECT_FALSE(v1 != v2);
    EXPECT_TRUE(v1 != v3);
    EXPECT_FALSE(v1 == v3);
}

TEST(VectorTest, CopySemantics) {
    Vec3 v1{1.0, 2.0, 3.0};

    // Copy constructor
    Vec3 v2 = v1;
    EXPECT_EQ(v1, v2);

    // Copy assignment
    Vec3 v3;
    v3 = v1;
    EXPECT_EQ(v1, v3);

    // Modify copy, original should be unchanged
    v2[0] = 999.0;
    EXPECT_NE(v1, v2);
    EXPECT_EQ(v1[0], 1.0);
}

TEST(VectorTest, MoveSemantics) {
    Vec3 v1{1.0, 2.0, 3.0};
    Vec3 original = v1;

    // Move constructor
    Vec3 v2 = std::move(v1);
    EXPECT_EQ(v2, original);

    // Move assignment
    Vec3 v3;
    Vec3 v4{4.0, 5.0, 6.0};
    Vec3 v4_copy = v4;
    v3 = std::move(v4);
    EXPECT_EQ(v3, v4_copy);
}